### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jjmmbb** [sahilph/umbrel-HTTPSizer#3]
First at all, amazing job! Thank you.

Initially the certificate generated for umbrel.local and localhost. I would like to suggest include also the host umbrel.

1. umbrel.local
2. umbrel
3. localhost

Just to keep it working on tailscale environments.

**Comment by sahilph** [comment]
> First at all, amazing job!.

Thank you. Appreciate it. 

 >I would like to suggest include also the host umbrel. 
>... 
>Just to keep it working on tailscale environments.

Yes, that's a good idea, I'll add it in the next update

**Comment by sahilph** [comment]
I have updated the app to support for tailscale hostname. That might solve the Nostr Relay issue as well.

I have also updated the wiki and added steps for trusting the Root CA for other OSs as well

**Comment by jjmmbb** [comment]
Thank you so much!
