### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by jjmmbb** [sahilph/umbrel-HTTPSizer#7]
I have found a way to get Let's Encrypt working on local and external network.

On this link you can see how to do it: https://youtu.be/qlcVx-k-02E

Basically instead of generate root certificates, you can copy the Let's Encrypt certificate from nginx proxy manager. And yes, you will need a domain name, but it can be DynDNS domains.

**Comment by sahilph** [comment]
This is beyond the scope of this app. 
The primary point of this app is to secure traffic in the local network, for that self signed certificates are just fine.

**Comment by jjmmbb** [comment]
sahilph, how do I diff the changes from auth and proxy packages modified to work with ssl? I would like to understand the changes made on those files.

**Comment by sahilph** [comment]
You can use the built-in github's compare tool:

https://github.com/sahilph/umbrel/compare/570acdabcab13ac237fba992f491d126fff30810..6f732ad7ea673d95bc8458d638b0f6151e387446

**Comment by jjmmbb** [comment]
Thank you!
